<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>자바스크립트 오류처리</h1>
    <p> try catch 같이 사용한다. </p>
    <p> try 블록에 오류를 테스트할 구문을 작성 </p>
    <p> catch 블록에 오류를 처리할 구문을 작성 </p>
    <pre>
        try{
        }catch(err){
        }
    </pre>
    <p id="test"></p>
    <hr>
    <p> 1~10 사이의 숫자를 입력 </p>
    <input type="text" id="numBox">
    <button type="button" id="btn">테스트</button>
    <p id="errText"></p>
    <pre>
    try{
        // 실제작성할 테스트 코드블록
    }
    catch(err){
        // 에러 코드블록
    }
    finally{
        // try catch 상관없이 실행되는 코드블록
    }
    
    자바스크립트 에러객체
    오류발생시 오류정보를 제공하는
    오류관련 객체가 내장되어있다.
    
    try catch 에서 catch(err) err-> Error객체
    err.name   오류 이름
    err.message   오류 메시지

    에러이름 종류
    1) EvalError
    2) RangeError
    3) ReferenceError
    4) SyntaxError
    5) TypeError
    6) URIError
    </pre>
    <p id="errText2"></p>
    <script src="./js/0526_1.js" defer></script>
</body>
</html>